### ISSUE TITLE
how to use for automatic workflow

### ISSUE THREAD

**Issue by aliworkshop** [koolkode/bpmn#6]
hi dear martin

Thanks alot for your package

i want to use this package for auto flow bpmn like share point workflower

how can i use  this package for handle automatic [https://github.com/bpmn-io/bpmn-js](url)  package ?

![screencast](https://user-images.githubusercontent.com/18111074/36978099-af506c46-2098-11e8-9250-b6007aa7b54a.gif)

**Comment by martinschroeder** [comment]
As far as i know bpmn-js just let you "draw" a BPMN diagram without any additional properties to make it executable. You can draw your diagram, but after that you need to add some info to the XML or use [camunda modeler](https://camunda.com/de/products/modeler/) to set "is executable" for your process and add PHP class names to service tasks (Java class) and condition expressions to flows after gateways.
