### ISSUE TITLE
how i can use visual bpm editor ?

### ISSUE THREAD

**Issue by vahidalvandi** [koolkode/bpmn#8]
i like to start a simple project with koolkode  , i think it provide a visual editor and db storage , but i can't Understand how it work.please explain it.
thank you ,

**Comment by martinschroeder** [comment]
You need to setup your database first, refer to the readme file, it explains the basic setup procedure. Once you got the engine up and running you have to use the `RepositoryService` to deploy a process (a process is just an XML file with a `.bpmn` extension).

You can use [camunda modeler](https://camunda.com/download/modeler/) as a visual editor to create your BPMN process. Save it as a file in your project directory and deploy it to the engine. Assuming you create your process in a file called `MyProcess.bpmn` and the "id" attribute of your process is set to "my-process" (set this in the visual editor) the code for deploying and launching a process instance is something like this:
```php
$repositoryService->deployProcess('MyProcess.bpmn');
$runtimeService->startProcessInstanceByKey('my-process');
```
